export type MarketIndex = 'sp500' | 'nasdaq100'

interface ConstituentInfo {
  symbol: string
  name: string
  sector: string
}

const SP500_TOP: ConstituentInfo[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', sector: 'Communication Services' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Communication Services' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Communication Services' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway (B)', sector: 'Financials' },
  { symbol: 'LLY', name: 'Eli Lilly & Co.', sector: 'Health Care' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financials' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financials' },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Health Care' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'XOM', name: 'Exxon Mobil Corp.', sector: 'Energy' },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Financials' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples' },
  { symbol: 'PG', name: 'Procter & Gamble Co.', sector: 'Consumer Staples' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care' },
  { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer Staples' },
  { symbol: 'HD', name: 'Home Depot Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'ORCL', name: 'Oracle Corp.', sector: 'Technology' },
  { symbol: 'MRK', name: 'Merck & Co.', sector: 'Health Care' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Health Care' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Technology' },
  { symbol: 'CVX', name: 'Chevron Corp.', sector: 'Energy' },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Financials' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
  { symbol: 'KO', name: 'Coca-Cola Co.', sector: 'Consumer Staples' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Health Care' },
  { symbol: 'LIN', name: 'Linde plc', sector: 'Materials' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { symbol: 'DIS', name: 'Walt Disney Co.', sector: 'Communication Services' },
  { symbol: 'WFC', name: 'Wells Fargo & Co.', sector: 'Financials' },
  { symbol: 'CSCO', name: 'Cisco Systems', sector: 'Technology' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health Care' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology' },
  { symbol: 'INTC', name: 'Intel Corp.', sector: 'Technology' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Technology' },
  { symbol: 'IBM', name: 'IBM Corp.', sector: 'Technology' },
  { symbol: 'GE', name: 'GE Aerospace', sector: 'Industrials' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication Services' },
  { symbol: 'AXP', name: 'American Express', sector: 'Financials' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Technology' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Health Care' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Technology' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Health Care' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Discretionary' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Health Care' },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Financials' },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication Services' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials' },
  { symbol: 'LOW', name: "Lowe's Companies", sector: 'Consumer Discretionary' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financials' },
  { symbol: 'UNP', name: 'Union Pacific', sector: 'Industrials' },
  { symbol: 'RTX', name: 'RTX Corp.', sector: 'Industrials' },
  { symbol: 'SPGI', name: 'S&P Global', sector: 'Financials' },
  { symbol: 'SYK', name: 'Stryker Corp.', sector: 'Health Care' },
  { symbol: 'NEE', name: 'NextEra Energy', sector: 'Utilities' },
  { symbol: 'HON', name: 'Honeywell Intl.', sector: 'Industrials' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Health Care' },
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Health Care' },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Financials' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financials' },
  { symbol: 'BSX', name: 'Boston Scientific', sector: 'Health Care' },
  { symbol: 'ADP', name: 'ADP Inc.', sector: 'Industrials' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb', sector: 'Health Care' },
  { symbol: 'ETN', name: 'Eaton Corp.', sector: 'Industrials' },
  { symbol: 'KLAC', name: 'KLA Corp.', sector: 'Technology' },
  { symbol: 'CB', name: 'Chubb Ltd.', sector: 'Financials' },
  { symbol: 'DE', name: 'Deere & Co.', sector: 'Industrials' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Health Care' },
  { symbol: 'FI', name: 'Fiserv Inc.', sector: 'Financials' },
  { symbol: 'SO', name: 'Southern Co.', sector: 'Utilities' },
  { symbol: 'DUK', name: 'Duke Energy', sector: 'Utilities' },
  { symbol: 'CME', name: 'CME Group', sector: 'Financials' },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer Staples' },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer Staples' },
  { symbol: 'MMC', name: 'Marsh & McLennan', sector: 'Financials' },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer Discretionary' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', sector: 'Financials' },
  { symbol: 'APH', name: 'Amphenol Corp.', sector: 'Technology' },
  { symbol: 'SHW', name: 'Sherwin-Williams', sector: 'Materials' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financials' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Technology' },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Financials' },
  { symbol: 'MCO', name: "Moody's Corp.", sector: 'Financials' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'Health Care' },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Health Care' },
]

const NASDAQ100: ConstituentInfo[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', sector: 'Technology' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', sector: 'Technology' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', sector: 'Communication Services' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Communication Services' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Communication Services' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer Staples' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology' },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples' },
  { symbol: 'INTC', name: 'Intel Corp.', sector: 'Technology' },
  { symbol: 'INTU', name: 'Intuit Inc.', sector: 'Technology' },
  { symbol: 'CSCO', name: 'Cisco Systems', sector: 'Technology' },
  { symbol: 'AMAT', name: 'Applied Materials', sector: 'Technology' },
  { symbol: 'CMCSA', name: 'Comcast Corp.', sector: 'Communication Services' },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Health Care' },
  { symbol: 'MU', name: 'Micron Technology', sector: 'Technology' },
  { symbol: 'BKNG', name: 'Booking Holdings', sector: 'Consumer Discretionary' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Health Care' },
  { symbol: 'HON', name: 'Honeywell Intl.', sector: 'Industrials' },
  { symbol: 'LRCX', name: 'Lam Research', sector: 'Technology' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', sector: 'Health Care' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', sector: 'Health Care' },
  { symbol: 'KLAC', name: 'KLA Corp.', sector: 'Technology' },
  { symbol: 'PANW', name: 'Palo Alto Networks', sector: 'Technology' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Technology' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', sector: 'Technology' },
  { symbol: 'ADP', name: 'ADP Inc.', sector: 'Industrials' },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Health Care' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', sector: 'Technology' },
  { symbol: 'MDLZ', name: 'Mondelez International', sector: 'Consumer Staples' },
  { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Financials' },
  { symbol: 'CTAS', name: 'Cintas Corp.', sector: 'Industrials' },
  { symbol: 'MAR', name: 'Marriott International', sector: 'Consumer Discretionary' },
  { symbol: 'MRVL', name: 'Marvell Technology', sector: 'Technology' },
  { symbol: 'CEG', name: 'Constellation Energy', sector: 'Utilities' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", sector: 'Consumer Discretionary' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'CSX', name: 'CSX Corp.', sector: 'Industrials' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Technology' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'Technology' },
  { symbol: 'DASH', name: 'DoorDash Inc.', sector: 'Consumer Discretionary' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', sector: 'Industrials' },
  { symbol: 'DXCM', name: 'DexCom Inc.', sector: 'Health Care' },
  { symbol: 'TTD', name: 'The Trade Desk', sector: 'Technology' },
  { symbol: 'MNST', name: 'Monster Beverage', sector: 'Consumer Staples' },
  { symbol: 'ROP', name: 'Roper Technologies', sector: 'Industrials' },
  { symbol: 'AZN', name: 'AstraZeneca', sector: 'Health Care' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', sector: 'Technology' },
  { symbol: 'ODFL', name: 'Old Dominion Freight', sector: 'Industrials' },
  { symbol: 'FAST', name: 'Fastenal Co.', sector: 'Industrials' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', sector: 'Consumer Staples' },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication Services' },
  { symbol: 'GEHC', name: 'GE HealthCare', sector: 'Health Care' },
  { symbol: 'VRSK', name: 'Verisk Analytics', sector: 'Industrials' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', sector: 'Health Care' },
  { symbol: 'CTSH', name: 'Cognizant Technology', sector: 'Technology' },
  { symbol: 'EXC', name: 'Exelon Corp.', sector: 'Utilities' },
  { symbol: 'LULU', name: 'Lululemon Athletica', sector: 'Consumer Discretionary' },
  { symbol: 'KHC', name: 'Kraft Heinz Co.', sector: 'Consumer Staples' },
  { symbol: 'BKR', name: 'Baker Hughes', sector: 'Energy' },
  { symbol: 'ON', name: 'ON Semiconductor', sector: 'Technology' },
  { symbol: 'XEL', name: 'Xcel Energy', sector: 'Utilities' },
  { symbol: 'ZS', name: 'Zscaler Inc.', sector: 'Technology' },
  { symbol: 'DDOG', name: 'Datadog Inc.', sector: 'Technology' },
  { symbol: 'TEAM', name: 'Atlassian Corp.', sector: 'Technology' },
  { symbol: 'ANSS', name: 'ANSYS Inc.', sector: 'Technology' },
  { symbol: 'CDW', name: 'CDW Corp.', sector: 'Technology' },
  { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'Health Care' },
  { symbol: 'ILMN', name: 'Illumina Inc.', sector: 'Health Care' },
  { symbol: 'MDB', name: 'MongoDB Inc.', sector: 'Technology' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication Services' },
  { symbol: 'SPLK', name: 'Splunk Inc.', sector: 'Technology' },
  { symbol: 'DLTR', name: 'Dollar Tree', sector: 'Consumer Discretionary' },
]

export function getConstituents(market: MarketIndex): ConstituentInfo[] {
  switch (market) {
    case 'sp500':
      return SP500_TOP
    case 'nasdaq100':
      return NASDAQ100
    default:
      return []
  }
}
